paginate: 5
paginate_path: "/blog/page:num"
name: Security7
description: "Security7 is a network and security systems integrator. We are experienced IT professionals and help businesses."
url: "http://www.security7.net"

slideshow:
  - image_path: /images/rev/slider01-img01.png
    title: Got an IT Security, Performance or Integration Problem?<br />Get Immediate, Expert Technical Support.
    text: When it’s taking too long to troubleshoot your Cisco, Juniper, Check Point and Fortinet firewall,<br />or get other day-to-day issues with IT hardware and software resolved, it’s time to work with people who know about VPNs,<br />configuring firewalls, combatting advanced threats, and delivering responsive expert technical support.<br />Learn more about all the ways we can help.
    link_label: Learn more
    link_url: #
  - image_path: /images/rev/slider01-img01.png
    title: Got an IT Security, Performance or Integration Problem?<br />Get Immediate, Expert Technical Support.
    text: When it’s taking too long to troubleshoot your Cisco, Juniper, Check Point and Fortinet firewall,<br />or get other day-to-day issues with IT hardware and software resolved, it’s time to work with people who know about VPNs,<br />configuring firewalls, combatting advanced threats, and delivering responsive expert technical support.<br />Learn more about all the ways we can help.
    link_label: Learn more
    link_url: #  